# Rename this file to languages.toml to enable multilingual support
# 文件: config/_default/languages.toml
[zh-cn]
  languageName = "中文"
  languagedirection = "ltr"
  title = "些许风霜" 
  description = "不过些许风霜罢了."
  weight = 1
