# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/bitfrost7"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibibli"
name = "Bilibili"
url = "https://space.bilibili.com/250535370"

[social.params]
icon="brand-bilibili"
